import React, { createContext, useContext, useState } from 'react';

export type LangCode = 'en' | 'fr';

const translations: Record<LangCode, Record<string, string>> = {
  en: {
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.clients': 'Clients',
    'nav.invoices': 'Invoices',
    'nav.transactions': 'Transactions',
    'nav.expenses': 'Expenses',
    'nav.reports': 'Reports',
    'nav.team': 'Team',
    'nav.settings': 'Settings',
    // Topbar
    'topbar.welcome': 'Welcome back',
    'topbar.managing': 'Managing',
    'topbar.default_subtitle': 'Manage your finances efficiently',
    'topbar.search_placeholder': 'Search pages, features, or records...',
    'topbar.profile': 'Profile & Settings',
    'topbar.signout': 'Sign Out',
    'topbar.notifications': 'Notifications',
    'topbar.unread': 'unread',
    'topbar.no_notifications': 'No unread notifications',
    'topbar.caught_up': "You're all caught up",
    'topbar.loading_notifications': 'Loading notifications...',
    // Common
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.download_pdf': 'Download PDF',
    'common.na': 'N/A',
      'common.actions': 'Actions',
      'common.view': 'View',
      'common.edit': 'Edit',
      'common.back': 'Back',
      'common.save_and_send': 'Save & send',
      'common.client': 'Client',
    'common.clear_filter': 'Clear filter',
    'common.filtered_showing': 'Filtered: showing',
    'common.unknown_error': 'Unknown error',
    'common.your_company': 'Your Company',
    // Status
    'status.paid': 'Paid',
    'status.in_progress': 'Pending',
    'status.overdue': 'Overdue',
    'status.draft': 'Draft',
    'status.cancelled': 'Cancelled',
    'status.pending': 'Pending',
    'status.sent': 'Sent',
    // Dashboard
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.overview': 'Overview',
    'dashboard.greeting_morning': 'Good morning',
    'dashboard.greeting_afternoon': 'Good afternoon',
    'dashboard.greeting_evening': 'Good evening',
    'dashboard.greeting_night': 'Good night',
    'dashboard.subtitle': 'Here is how your business is performing today.',
    'dashboard.export_summary_pdf': 'Export summary PDF',
    'dashboard.create_invoice': 'Create invoice',
    'dashboard.income': 'Income',
    'dashboard.expenses': 'Expenses',
    'dashboard.margin': 'margin',
    'dashboard.spend_vs_revenue': 'spend vs revenue',
    'dashboard.pending_amount': 'Pending amount',
    'dashboard.outstanding_unpaid': 'Outstanding from unpaid invoices',
    'dashboard.profit': 'Profit',
    'dashboard.invoices_tracked': 'invoices tracked this cycle',
    'dashboard.cancelled': 'cancelled',
    'dashboard.cashflow_trends': 'Cashflow trends',
    'dashboard.last_6_months': 'Last 6 months of income, expenses, pending, and draft amounts.',
    'dashboard.invoice_health': 'Invoice health',
    'dashboard.invoice_health_subtitle': 'Current invoice status distribution.',
    'dashboard.no_data': 'No data',
    'dashboard.latest_invoices': 'Latest invoices',
    'dashboard.view_all': 'View all',
    'dashboard.no_invoices': 'No invoices yet. Create your first invoice to start tracking collections.',
    'dashboard.client_label': 'Client',
    'dashboard.income_vs_expenses': 'Income vs expenses',
    'dashboard.recent_period': 'Recent period',
    'dashboard.transactions_feed': 'Transactions feed',
    'dashboard.latest_activity': 'Latest business activity',
    'dashboard.no_transactions': 'No recent transactions to show.',
    'dashboard.add_new_client': 'Add new client',
    'dashboard.add_new_client_desc': 'Create and organize client profiles.',
    'dashboard.create_invoice_desc': 'Generate and share invoices quickly.',
    'dashboard.add_expense': 'Add expense',
    'dashboard.add_expense_desc': 'Keep spending records up to date.',
    'dashboard.summary_pdf_title': 'Generate Summary PDF',
    'dashboard.summary_pdf_message': 'This will generate and download a comprehensive financial summary PDF. This may take a few seconds.',
    'dashboard.download_pdf': 'Download PDF',
    'dashboard.summary_pdf_error': 'Failed to download summary PDF',
    'dashboard.client_invoice': 'Client invoice',
    'dashboard.expense_title': 'Expense',
    'dashboard.operational_expense': 'Operational expense',
    'dashboard.collected': 'Collected',    // Search
    'search.title': 'Search',
    'search.results_for': 'Results for',
    'search.type_hint': 'Type in the top bar to search',
    'search.helper': 'Search across pages, clients, invoices, and expenses from the navbar.',
    'search.loading': 'Searching records...',
    'search.error': 'Failed to load search data. Please try again.',
    'search.no_matches': 'No matches found in pages, clients, invoices, or expenses.',
    'search.pages': 'Pages',
    'search.clients': 'Clients',
    'search.invoices': 'Invoices',
    'search.expenses': 'Expenses',
    'search.no_contact': 'No contact',
    'search.client_unavailable': 'Client unavailable',
    'search.due': 'Due',
    'search.unnamed_supplier': 'Unnamed supplier',
    'search.uncategorized': 'Uncategorized',
    'search.nav_dashboard_desc': 'Overview of business performance and quick actions.',
    'search.nav_workspace': 'Workspace',
    'search.nav_clients_desc': 'Manage clients, contacts, and account history.',
    'search.nav_crm': 'CRM',
    'search.nav_invoices_desc': 'Create invoices and monitor payment status.',
    'search.nav_billing': 'Billing',
    'search.nav_expenses_desc': 'Track spending, categories, and supplier costs.',
    'search.nav_finance': 'Finance',
    'search.nav_reports_desc': 'Review revenue, costs, and profitability insights.',
    'search.nav_analytics': 'Analytics',
    'search.nav_team_desc': 'Invite and manage teammates and roles.',
    'search.nav_admin': 'Administration',
    'search.nav_settings_desc': 'Configure company profile, branding, and preferences.',
    // Reports
    'reports.title': 'Financial Reports',
    'reports.export_pdf': 'Export PDF',
    'reports.export_csv': 'Export CSV',
    'reports.filter_title': 'Filter Reports',
    'reports.start_date': 'Start Date',
    'reports.end_date': 'End Date',
    'reports.generate_report': 'Generate Report',
    'reports.loading': 'Loading...',
    'reports.total_revenue': 'Total Revenue',
    'reports.total_expenses': 'Total Expenses',
    'reports.net_profit': 'Net Profit',
    'reports.margin': 'Margin',
    'reports.net_cashflow': 'Net cashflow trend',
    'reports.collected_minus_expenses': 'Collected - Expenses',
    'reports.no_trend': 'No trend data for selected period',
    'reports.top_expense_categories': 'Top expense categories',
    'reports.highest_spend': 'Highest spend categories',
    'reports.no_expense_categories': 'No expense categories for selected period',
    'reports.invoices_summary': 'Invoices Summary',
    'reports.total_paid': 'Total Paid',
    'reports.total_pending': 'Total Pending',
    'reports.collected': 'Collected',
    'reports.total_invoices': 'Total Invoices',
    'reports.expenses_summary': 'Expenses Summary',
    'reports.total_records': 'Total Records',
    'reports.client_performance': 'Client Performance',
    'reports.view_all': 'View All',
    'reports.show_less': 'Show Less',
    'reports.loading_performance': 'Loading performance data...',
    'reports.performance_error': 'Failed to load performance data',
    'reports.collection_rate': 'Collection Rate',
    'reports.paid_rate': 'Paid Rate',
    'reports.score': 'Score',
    'reports.empty_prompt': 'Select a date range and click "Generate Report" to view financial data',
    'reports.ai_forecast_title': 'AI-Powered Forecast',
    'reports.ai_forecast_desc': 'Click the button below to generate a 90-day cash flow forecast based on your historical data. This feature uses AI to predict future financial trends.',
    'reports.generate_forecast': 'Generate 90-Day Forecast',
    'reports.generating_forecast': 'Generating Forecast...',
    'reports.ai_loading': 'AI is analyzing your data...',
    'reports.pdf_title': 'FiinFlow Financial Report',
    'reports.pdf_period': 'Period',
    'reports.pdf_all_time': 'All time',
    'reports.pdf_present': 'Present',
    'reports.pdf_summary_title': 'Financial Summary',
    'reports.pdf_metric': 'Metric',
    'reports.pdf_value': 'Value',
    'reports.pdf_invoices': 'Invoices',
    'reports.pdf_expenses': 'Expenses',
    'reports.pdf_invoice_number': 'Invoice #',
    'reports.pdf_client': 'Client',
    'reports.pdf_amount': 'Amount',
    'reports.pdf_status': 'Status',
    'reports.pdf_due_date': 'Due Date',
    'reports.pdf_supplier': 'Supplier',
    'reports.pdf_category': 'Category',
    'reports.pdf_date': 'Date',
    'reports.csv_summary': 'FINANCIAL SUMMARY',
    'reports.csv_invoices': 'INVOICES',
    'reports.csv_expenses': 'EXPENSES',
    'reports.csv_period': 'Period',
    // Common (extended)
    'common.save': 'Save',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.status': 'Status',
    'common.role': 'Role',
    // Login
    'login.back_home': 'Back to home',
    'login.title': 'Sign in to your account',
    'login.subtitle': 'Use your workspace credentials to continue.',
    'login.email_label': 'Email address',
    'login.email_placeholder': 'you@company.com',
    'login.password_label': 'Password',
    'login.password_placeholder': 'Enter your password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.signing_in': 'Signing in...',
    'login.sign_in': 'Sign in',
    'login.no_account': "Don't have an account?",
    'login.start_setup': 'Start a free setup',
    'login.success': 'Logged in successfully',
    'login.error_default': 'Login failed. Please check your credentials.',
    // Not Found
    'notfound.code': 'Error 404',
    'notfound.title': 'Page not found',
    'notfound.subtitle': 'The page you requested does not exist or was moved.',
    'notfound.back': 'Go back',
    'notfound.to_dashboard': 'Go to dashboard',
    'notfound.to_home': 'Go to home',
    // Password rules
    'password.rule.min_length': 'At least 8 characters',
    'password.rule.uppercase': 'At least one uppercase letter',
    'password.rule.lowercase': 'At least one lowercase letter',
    'password.rule.number': 'At least one number',
    'password.rule.special': 'At least one special character',
    'password.error_strong': 'Password must be strong: 8+ characters, uppercase, lowercase, number, and special character.',
    // Change Password
    'change_password.title': 'Change Password',
    'change_password.current_label': 'Current Password',
    'change_password.new_label': 'New Password',
    'change_password.confirm_label': 'Confirm New Password',
    'change_password.mismatch': 'New passwords do not match',
    'change_password.success': 'Password changed successfully!',
    'change_password.success_toast': 'Password changed successfully',
    'change_password.error_default': 'Failed to change password',
    'change_password.changing': 'Changing...',
    'change_password.submit': 'Change Password',
    // Forgot Password
    'forgot_password.toast_sent': 'If the account exists, a reset email has been sent.',
    'forgot_password.success_title': 'Check Your Email',
    'forgot_password.success_body': 'If an account exists with this email address, you will receive password reset instructions.',
    'forgot_password.success_hint': 'Please check your inbox and spam folder.',
    'forgot_password.back_login': 'Back to Login',
    'forgot_password.title': 'Forgot Password?',
    'forgot_password.subtitle': "Enter your email address and we'll send you a link to reset your password.",
    'forgot_password.email_label': 'Email Address',
    'forgot_password.email_placeholder': 'your@email.com',
    'forgot_password.sending': 'Sending...',
    'forgot_password.send_link': 'Send Reset Link',
    'forgot_password.remember_prompt': 'Remember your password?',
    'forgot_password.sign_in': 'Sign In',
    'forgot_password.general_login': 'Go to General Login',
    // Reset Password
    'reset_password.invalid_link_error': 'Invalid or missing reset link',
    'reset_password.mismatch': 'Passwords do not match',
    'reset_password.success_toast': 'Password reset successful',
    'reset_password.error_default': 'Failed to reset password. The link may have expired. Please request a new reset link.',
    'reset_password.invalid_title': 'Invalid Link',
    'reset_password.invalid_body': 'This password reset link is invalid or has expired.',
    'reset_password.request_new_link': 'Request New Reset Link',
    'reset_password.success_title': 'Password Reset Successful!',
    'reset_password.success_body': 'Your password has been reset successfully. You can now log in with your new password.',
    'reset_password.redirecting': 'Redirecting to login page...',
    'reset_password.title': 'Reset Password',
    'reset_password.subtitle': 'Enter your new password below',
    'reset_password.new_label': 'New Password',
    'reset_password.new_placeholder': 'Enter new password',
    'reset_password.hide': 'Hide',
    'reset_password.show': 'Show',
    'reset_password.confirm_label': 'Confirm New Password',
    'reset_password.confirm_placeholder': 'Confirm new password',
    'reset_password.resetting': 'Resetting Password...',
    'reset_password.submit': 'Reset Password',
    'reset_password.remember_prompt': 'Remember your password?',
    'reset_password.sign_in': 'Sign In',
    // Set Password
    'set_password.invalid_link_error': 'Invalid or missing invitation link',
    'set_password.mismatch': 'Passwords do not match',
    'set_password.success_toast': 'Password set successfully',
    'set_password.error_default': 'Failed to set password. Please try again or request a new invitation.',
    'set_password.invalid_title': 'Invalid Link',
    'set_password.invalid_body': 'This invitation link is invalid or has expired. Please contact your administrator for a new invitation.',
    'set_password.go_login': 'Go to Login',
    'set_password.success_title': 'Password Set Successfully!',
    'set_password.success_body': 'Your password has been set. You can now log in to your workspace.',
    'set_password.redirecting': 'Redirecting to login page...',
    'set_password.welcome': 'Welcome!',
    'set_password.subtitle': 'Set your password to join FiinFlow',
    'set_password.title': 'Set Your Password',
    'set_password.password_label': 'Password',
    'set_password.password_placeholder': 'Enter your password',
    'set_password.confirm_label': 'Confirm Password',
    'set_password.confirm_placeholder': 'Confirm your password',
    'set_password.hide': 'Hide',
    'set_password.show': 'Show',
    'set_password.setting': 'Setting Password...',
    'set_password.submit': 'Set Password & Continue',
    'set_password.already_prompt': 'Already have an account?',
    'set_password.sign_in': 'Sign In',
    // Company Setup
    'company_setup.consent_required': 'Please agree to the research participation consent before proceeding.',
    'company_setup.success_toast': 'Company created successfully. You can now log in.',
    'company_setup.error_default': 'Failed to create company',
    'company_setup.back_home': 'Back to home',
    'company_setup.title': 'Create your workspace',
    'company_setup.subtitle': 'Set up your company account and get started.',
    'company_setup.name_label': 'Company name',
    'company_setup.name_placeholder': 'Company name',
    'company_setup.email_label': 'Company email',
    'company_setup.email_placeholder': 'company@email.com',
    'company_setup.phone_label': 'Phone number',
    'company_setup.phone_placeholder': '+250 XXX XXX XXX',
    'company_setup.industry_label': 'Industry (optional)',
    'company_setup.industry_placeholder': 'Industry',
    'company_setup.address_label': 'Company address',
    'company_setup.address_placeholder': 'Company address',
    'company_setup.password_label': 'Create password',
    'company_setup.password_placeholder': 'Create a strong password',
    'company_setup.confirm_label': 'Confirm password',
    'company_setup.confirm_placeholder': 'Re-enter password',
    'company_setup.password_mismatch': 'Passwords do not match.',
    'company_setup.consent_blurb': 'FiinFlow is part of a capstone research project at African Leadership University. Data is used for academic evaluation and deleted after the pilot study.',
    'company_setup.consent_label': 'I consent to participate in the FiinFlow research pilot.',
    'company_setup.consent_link': 'Read full consent information',
    'company_setup.creating': 'Creating...',
    'company_setup.submit': 'Create account',
    'company_setup.already_prompt': 'Already have an account?',
    'company_setup.sign_in': 'Log in',
    // User Setup
    'user_setup.success_toast': 'Admin user created successfully',
    'user_setup.error_default': 'Failed to create admin user',
    'user_setup.title': 'Create Admin User',
    'user_setup.subtitle': 'Set up the main administrator account',
    'user_setup.name_label': 'Full Name *',
    'user_setup.name_placeholder': 'John Doe',
    'user_setup.email_label': 'Email *',
    'user_setup.email_placeholder': 'admin@company.com',
    'user_setup.phone_label': 'Phone (Optional)',
    'user_setup.phone_placeholder': '+250 XXX XXX XXX',
    'user_setup.role_label': 'Role:',
    'user_setup.role_value': 'Administrator (Full access)',
    'user_setup.creating': 'Creating...',
    'user_setup.submit': 'Create Admin & Continue',
    // Research Consent
    'research_consent.org': 'African Leadership University',
    'research_consent.title': 'Research Consent Information',
    'research_consent.about_title': 'About This Study',
    'research_consent.about_body': 'FiinFlow is a capstone project developed at African Leadership University (ALU). This pilot study evaluates whether FiinFlow can help small and medium enterprises (SMEs) in Rwanda manage their finances more efficiently. Your participation helps us understand real-world usability and improve the system.',
    'research_consent.data_title': 'What Data We Collect',
    'research_consent.data_company_label': 'Company information:',
    'research_consent.data_company_body': 'Business name, email, phone, and address (provided during registration).',
    'research_consent.data_financial_label': 'Financial records:',
    'research_consent.data_financial_body': 'Invoices, expenses, and client details you enter into the system.',
    'research_consent.data_usage_label': 'Usage patterns:',
    'research_consent.data_usage_body': 'Which features you use and how often, to evaluate system usability.',
    'research_consent.protect_title': 'How We Protect Your Data',
    'research_consent.protect_item_1': 'All passwords are hashed using bcrypt and never stored in plain text.',
    'research_consent.protect_item_2': "Your company's data is isolated from other companies through token-based authentication.",
    'research_consent.protect_item_3': 'Role-based access control ensures only authorized team members see sensitive data.',
    'research_consent.protect_item_4': 'Data will be stored securely and deleted after the pilot study concludes.',
    'research_consent.rights_title': 'Your Rights as a Participant',
    'research_consent.rights_item_1': 'Participation is completely voluntary. You are not obligated to use FiinFlow.',
    'research_consent.rights_item_2': 'You may withdraw at any time without penalty or negative consequences.',
    'research_consent.rights_item_3': 'You may request that your data be deleted at any point during or after the study.',
    'research_consent.rights_item_4': 'You have the right to ask questions about the study at any time.',
    'research_consent.withdraw_title': 'How to Withdraw',
    'research_consent.withdraw_body': 'To withdraw from the study, simply stop using FiinFlow and contact the researcher. All your data will be permanently deleted from the system within 7 days of your withdrawal request. There is no penalty for withdrawing.',
    'research_consent.contact_title': 'Contact the Researcher',
    'research_consent.contact_intro': 'If you have any questions about this study, please contact:',
    'research_consent.contact_name': 'Grace Munezero',
    'research_consent.contact_org': 'African Leadership University, Kigali, Rwanda',
    'research_consent.back_setup': 'Back to Company Setup',
    // Analytics
    'analytics.loading': 'Loading analytics...',
    'analytics.no_data': 'No analytics data available',
    'analytics.income': 'Income',
    'analytics.expense': 'Expense',
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Visualize your spending patterns and financial insights',
    'analytics.top_category': 'Top Category',
    'analytics.total_income': 'Total Income (YTD)',
    'analytics.total_expense': 'Total Expense (YTD)',
    'analytics.income_vs_expense': 'Income vs Expense',
    'analytics.spending_by_category': 'Spending by Category',
    'analytics.summary': 'Summary',
    'analytics.savings_rate': 'Savings Rate',
    'analytics.avg_expense': 'Average Monthly Expense',
    'analytics.avg_income': 'Average Monthly Income',
    // Team
    'team.loading': 'Loading team members...',
    'team.title': 'Team Members',
    'team.subtitle': 'Manage users who have access to your company workspace',
    'team.invite_user': '+ Invite User',
    'team.add_member': '+ Add Member',
    'team.role_label': 'Role',
    'team.joined_label': 'Joined',
    'team.resend_invite': 'Resend invite',
    'team.cancel_invite': 'Cancel invite',
    'team.edit_member': 'Edit member',
    'team.remove_member': 'Remove member',
    'team.table_name': 'Name',
    'team.table_email': 'Email',
    'team.table_phone': 'Phone',
    'team.table_role': 'Role',
    'team.table_status': 'Status',
    'team.table_joined': 'Joined',
    'team.empty_title': 'No team members yet',
    'team.empty_subtitle': 'Invite or add team members to collaborate on your workspace',
    'team.add_team_member': '+ Add Team Member',
    'team.edit_title': 'Edit Team Member',
    'team.add_title': 'Add Team Member',
    'team.name_label': 'Name *',
    'team.name_placeholder': 'John Doe',
    'team.email_label': 'Email *',
    'team.email_placeholder': 'john@example.com',
    'team.password_edit_label': 'Password (leave blank to keep current)',
    'team.password_new_label': 'Password *',
    'team.password_edit_placeholder': 'Enter new password',
    'team.password_new_placeholder': 'Create a strong password',
    'team.phone_label': 'Phone',
    'team.phone_placeholder': '+250 XXX XXX XXX',
    'team.role_staff_desc': 'Staff - Can create drafts only',
    'team.role_finance_manager_desc': 'Finance Manager - Full access to invoices/expenses',
    'team.role_admin_desc': 'Admin - Full system access',
    'team.role_super_admin_desc': 'Super Admin - Global system access',
    'team.update': 'Update',
    'team.invite_title': 'Invite User',
    'team.invite_subtitle': 'Send an invitation email to a new user. They will receive a link to set their password and join your workspace.',
    'team.invite_note': 'The user will receive an email with a secure link to set their password. The link will be valid for 7 days.',
    'team.send_invite': 'Send Invitation',
    'team.remove_title': 'Remove Team Member',
    'team.remove_message': 'Are you sure you want to remove this team member? They will lose access to this workspace.',
    'team.remove_confirm': 'Remove',
    'team.role_super_admin': 'Super Admin',
    'team.role_admin': 'Admin',
    'team.role_finance_manager': 'Finance Manager',
    'team.role_staff': 'Staff',
    'team.status_pending': 'Pending',
    'team.status_active': 'Active',
    'team.status_suspended': 'Suspended',
    'team.updated_success': 'Team member updated successfully',
    'team.created_success': 'Team member added successfully',
    'team.save_error': 'Failed to save team member. Please try again.',
    'team.removed_success': 'Team member removed successfully',
    'team.delete_error': 'Failed to delete team member',
    'team.invite_success': 'User invited successfully. Invitation email sent.',
    'team.invite_error': 'Failed to invite user. Please try again.',
    'team.resend_success': 'Invitation email resent successfully',
    'team.resend_error': 'Failed to resend invitation. Please try again.',
    // Clients
    'clients.phone_validation': 'Phone number must contain at least 10 digits.',
    'clients.updated_success': 'Client updated successfully',
    'clients.created_success': 'Client created successfully',
    'clients.save_error': 'Failed to save client. Please try again.',
    'clients.deleted_success': 'Client deleted successfully',
    'clients.delete_error': 'Failed to delete client',
    'clients.loading': 'Loading clients...',
    'clients.title': 'Clients',
    'clients.add_client': '+ Add Client',
    'clients.empty_title': 'No clients yet',
    'clients.empty_subtitle': 'Add your first client to start creating invoices',
    'clients.email_label': 'Email',
    'clients.phone_label': 'Phone',
    'clients.view_client': 'View client',
    'clients.edit_client': 'Edit client',
    'clients.delete_client': 'Delete client',
    'clients.table_name': 'Name',
    'clients.table_contact': 'Contact Person',
    'clients.table_email': 'Email',
    'clients.table_phone': 'Phone',
    'clients.edit_title': 'Edit Client',
    'clients.add_title': 'Add New Client',
    'clients.form_company_name': 'Company Name *',
    'clients.form_contact': 'Contact Person *',
    'clients.form_email': 'Email *',
    'clients.form_phone': 'Phone *',
    'clients.form_address': 'Address *',
    'clients.update': 'Update',
    'clients.create': 'Create',
      'clients.delete_title': 'Delete Client',
      'clients.delete_message': 'Are you sure you want to delete this client? This action cannot be undone.',
      // Client Detail
      'client_detail.loading': 'Loading client...',
      'client_detail.not_found': 'Client not found',
      'client_detail.back_clients': 'Back to clients',
      'client_detail.client_since': 'Client since',
      'client_detail.revenue': 'Revenue',
      'client_detail.expenses': 'Expenses',
      'client_detail.profit': 'Profit',
      'client_detail.net_profit': 'Net profit',
      'client_detail.payment_rate': 'Payment rate',
      'client_detail.currency_label': 'Currency',
      'client_detail.paid_invoices': 'paid invoices',
      'client_detail.records': 'records',
      'client_detail.revenue_minus_expenses': 'revenue - expenses',
      'client_detail.of': 'of',
      'client_detail.paid': 'paid',
      'client_detail.invoice_status_breakdown': 'Invoice status breakdown',
      'client_detail.invoices_label': 'invoices',
      'client_detail.invoice_label': 'invoice',
      'client_detail.revenue_vs_expenses': 'Revenue vs expenses',
      'client_detail.contact_info': 'Contact information',
      'client_detail.contact_person': 'Contact person',
      'client_detail.quick_stats': 'Quick stats',
      'client_detail.total_invoices': 'Total invoices',
      'client_detail.paid_invoices_label': 'Paid invoices',
      'client_detail.unpaid_invoices': 'Unpaid invoices',
      'client_detail.linked_expenses': 'Linked expenses',
      'client_detail.tab_invoices': 'Invoices',
      'client_detail.tab_expenses': 'Expenses',
      'client_detail.no_invoices': 'No invoices for this client',
      'client_detail.no_expenses': 'No expenses for this client',
      'client_detail.invoice_number': 'Invoice #',
      'client_detail.amount': 'Amount',
      'client_detail.due_date': 'Due date',
      'client_detail.status': 'Status',
      'client_detail.supplier': 'Supplier',
      'client_detail.category': 'Category',
      'client_detail.total': 'Total',
      'client_detail.remaining': 'Remaining',
      'client_detail.view_all': 'View all',
      'client_detail.show_less': 'Show less',
    // Transactions
    'transactions.title': 'Transactions',
    'transactions.tab_all': 'All',
    'transactions.tab_income': 'Income',
    'transactions.tab_expenses': 'Expenses',
    'transactions.search_placeholder': 'Search transactions...',
    'transactions.date': 'Date',
    'transactions.name': 'Name',
    'transactions.type': 'Type',
    'transactions.spent': 'Spent',
    'transactions.received': 'Received',
    'transactions.action': 'Action',
    'transactions.linked': 'Linked',
    'transactions.unlink': 'Unlink',
    'transactions.link': 'Link',
    'transactions.invoice': 'Invoice',
    'transactions.expense': 'Expense',
    'transactions.already_linked': 'This transaction is already linked.',
    'transactions.clear_filters': 'Clear filters',
    'transactions.empty_title': 'No transactions yet',
    'transactions.empty_subtitle': 'Once you record transactions they will appear here.',
    'transactions.empty_subtitle_filtered': 'No transactions match your filters.',
    'transactions.load_more': 'Load more',
    'transactions.loading': 'Loading transactions...',
      'transactions.delete_title': 'Delete Transaction',
      'transactions.delete_message': 'Are you sure you want to delete this transaction?',
      'transactions.delete_soon': 'Delete action will be available soon',
      'transactions.fallback_expense': 'Expense',
      'transactions.fallback_client': 'Client',
    // Expenses (table + header)
    'expenses.title': 'Expenses',
    'expenses.export_pdf': 'Export PDF',
    'expenses.add': '+ Add Expense',
    'expenses.filtered_showing': 'Filtered: showing',
    'expenses.table.supplier': 'Supplier',
    'expenses.table.category': 'Category',
    'expenses.table.created_at': 'Created',
    'expenses.table.total_amount': 'Total Amount',
    'expenses.table.amount_paid': 'Amount Paid',
    'expenses.table.remaining': 'Remaining',
      'expenses.table.due_date': 'Due Date',
      'expenses.table.status': 'Status',
      'expenses.table.actions': 'Actions',
      'expenses.clear_filter': 'Clear filter',
      'expenses.empty_title': 'No expenses yet',
      'expenses.empty_subtitle': 'Add your first expense to start tracking spending',
      'expenses.loading': 'Loading expenses...',
      'expenses.created_success': 'Expense created successfully',
      'expenses.create_failed': 'Failed to create expense',
      'expenses.deleted_success': 'Expense deleted successfully',
      'expenses.delete_failed': 'Failed to delete expense',
      'expenses.form_invalid_total': 'Please enter a valid total amount.',
      'expenses.form_negative_paid': 'Amount paid cannot be negative.',
      'expenses.form_paid_exceeds': 'Amount paid cannot exceed total amount.',
      'expenses.form_supplier_required': 'Supplier name is required.',
      'expenses.receipt_open_failed': 'Failed to open receipt.',
      'expenses.pdf_downloaded': 'Expenses report downloaded.',
      'expenses.pdf_failed': 'Failed to download expenses report.',
      'expenses.linked_success': 'Expense linked successfully.',
      'expenses.linked_updated': 'Linked amount applied. Remaining:',
      'expenses.linked_failed_apply': 'Failed to apply linked amount.',
      'expenses.mobile.total': 'Total',
      'expenses.mobile.paid': 'Paid',
      'expenses.mobile.remaining': 'Remaining',
      'expenses.mobile.due_date': 'Due date',
      'expenses.modal.create_title': 'Create Expense',
      'expenses.modal.linked_client': 'Linked client',
      'expenses.modal.no_linked_client': 'No linked client',
      'expenses.modal.supplier_name_required': 'Supplier name *',
      'expenses.modal.supplier_name': 'Supplier name',
      'expenses.modal.category': 'Category',
      'expenses.modal.custom_category_placeholder': 'Enter custom category',
      'expenses.modal.total_amount': 'Total amount',
      'expenses.modal.amount_paid': 'Amount paid',
      'expenses.modal.remaining_amount': 'Remaining amount',
      'expenses.modal.due_date': 'Due date',
      'expenses.modal.payment_method': 'Payment method',
      'expenses.modal.reference_number': 'Reference number',
      'expenses.modal.reference_placeholder': 'Transaction / receipt ref',
      'expenses.modal.description_notes': 'Description / notes',
      'expenses.modal.description_placeholder': 'Add details about this expense...',
      'expenses.modal.receipt_optional': 'Receipt (optional)',
      'expenses.modal.upload_receipt': 'Upload receipt',
      'expenses.modal.change_receipt': 'Change receipt',
      'expenses.modal.receipt_selected': 'Selected:',
      'expenses.modal.receipt_accepted': 'PDF, JPG, or PNG accepted',
      'expenses.modal.summary_title': 'Summary',
      'expenses.modal.summary_total': 'Total',
      'expenses.modal.summary_paid': 'Paid',
      'expenses.modal.summary_remaining': 'Remaining',
      'expenses.modal.tips_title': 'Tips',
      'expenses.modal.tip_supplier': 'Use a clear supplier name for reporting.',
      'expenses.modal.tip_reference': 'Add a reference to match bank statements.',
      'expenses.modal.tip_link_client': 'Link to a client to keep costs organized.',
      'expenses.modal.cancel': 'Cancel',
      'expenses.modal.create_button': 'Create expense',
      'expenses.confirm_delete_title': 'Delete expense',
      'expenses.confirm_delete_message': 'Are you sure you want to delete this expense? This action cannot be undone.',
      'expenses.confirm_delete_confirm': 'Delete',
      'expenses.confirm_delete_cancel': 'Cancel',
      'expenses.confirm_pdf_title': 'Download expenses report',
      'expenses.confirm_pdf_message': 'Generate and download a PDF report for expenses?',
      'expenses.confirm_pdf_confirm': 'Download PDF',
      'expenses.confirm_pdf_cancel': 'Cancel',
      'expenses.confirm_link_title': 'Link expense',
      'expenses.confirm_link_message_prefix': 'Link the expense',
      'expenses.confirm_link_message_suffix': 'to this transaction?',
      'expenses.confirm_link_confirm': 'Link',
      'expenses.confirm_link_cancel': 'Cancel',
    // Invoices (table + header)
    'invoices.title': 'Invoices',
    'invoices.create': 'Create Invoice',
    'invoices.table.number': 'Invoice #',
    'invoices.table.client': 'Client',
    'invoices.table.amount': 'Amount',
    'invoices.table.paid': 'Paid',
    'invoices.table.remaining': 'Remaining',
    'invoices.table.status': 'Status',
    'invoices.table.created': 'Created',
      'invoices.table.due_date': 'Due date',
      'invoices.type.tax': 'Tax Invoice',
      'invoices.loading': 'Loading invoices...',
      'invoices.empty_title': 'No invoices yet',
      'invoices.empty_subtitle': 'Create your first invoice to start tracking payments',
      'invoices.linked_success': 'Invoice linked successfully.',
      'invoices.linked_updated': 'Linked amount applied. Remaining:',
      'invoices.linked_failed_apply': 'Failed to apply linked amount.',
      'invoices.save_failed': 'Failed to save invoice',
      'invoices.save_send_failed': 'Failed to save and send invoice',
      'invoices.saved_draft': 'Invoice saved as draft',
      'invoices.saved_not_sent': 'Invoice saved but not sent',
      'invoices.sent_email_sent': 'Invoice sent and email delivered',
      'invoices.sent_email_failed': 'Invoice sent but email failed:',
      'invoices.sent_email_not_attempted': 'Invoice sent but email not attempted:',
      'invoices.updated_email_sent': 'Invoice updated and email sent',
      'invoices.updated_email_failed': 'Invoice updated but email failed:',
      'invoices.updated_email_not_attempted': 'Invoice updated but email not attempted:',
      'invoices.emailjs_missing_env': 'Email settings are missing. Please configure EmailJS environment variables.',
      'invoices.no_recipient_email': 'No recipient email found',
      'invoices.preview_title': 'Invoice preview',
      'invoices.preview_subtitle': 'Review before sending',
      'invoices.sending': 'Sending...',
      'invoices.bill_to': 'Bill to',
      'invoices.invoice_date': 'Invoice date',
      'invoices.due_date': 'Due date',
      'invoices.qty': 'Qty',
      'invoices.description': 'Description',
      'invoices.unit_price': 'Unit price',
      'invoices.amount': 'Amount',
      'invoices.subtotal': 'Subtotal',
      'invoices.sales_tax': 'Sales tax',
      'invoices.total': 'Total',
      'invoices.how_to_pay': 'How to pay',
      'invoices.pay_mobile_money': 'Pay via Mobile Money',
      'invoices.pay_bank_transfer': 'Bank transfer',
      'invoices.pay_use_reference': 'Use reference',
      'invoices.label.standard': 'STANDARD INVOICE',
      'invoices.label.proforma': 'PROFORMA INVOICE',
      'invoices.label.tax': 'TAX INVOICE',
      'invoices.label.commercial': 'COMMERCIAL INVOICE',
      'invoices.label.credit_note': 'CREDIT NOTE',
      'invoices.label.debit_note': 'DEBIT NOTE',
      'invoices.type.standard': 'Standard',
      'invoices.type.proforma': 'Proforma',
      'invoices.type.commercial': 'Commercial',
      'invoices.type.credit_note': 'Credit note',
      'invoices.type.debit_note': 'Debit note',
      'invoices.confirm_delete_title': 'Delete invoice',
      'invoices.confirm_delete_message': 'Are you sure you want to delete this invoice? This action cannot be undone.',
      'invoices.confirm_link_title': 'Link invoice',
      'invoices.confirm_link_message': 'Link invoice',
      'invoices.confirm_link_to': 'to',
      'invoices.confirm_link_confirm': 'Link',
      'invoices.modal.title_create': 'Create invoice',
      'invoices.modal.title_edit': 'Edit invoice',
      'invoices.modal.invoice_number': 'Invoice number',
      'invoices.modal.invoice_type': 'Invoice type',
      'invoices.modal.other_type': 'Other',
      'invoices.modal.custom_type_placeholder': 'Enter type',
      'invoices.modal.client': 'Client',
      'invoices.modal.select_client': 'Select client',
      'invoices.modal.bill_to': 'Bill to',
      'invoices.modal.currency': 'Currency',
      'invoices.modal.rwf_label': 'RWF (Rwandan Franc)',
      'invoices.modal.usd_label': 'USD (US Dollar)',
      'invoices.modal.invoice_total': 'Invoice total',
      'invoices.modal.due_date': 'Due date',
      'invoices.modal.description': 'Description',
      'invoices.modal.line_items': 'Line items',
      'invoices.modal.product_service_label': 'Product / service',
      'invoices.modal.product_service': 'Product or service',
      'invoices.modal.qty': 'Qty',
      'invoices.modal.rate': 'Rate',
      'invoices.modal.amount': 'Amount',
      'invoices.modal.add_line_item': 'Add line item',
      'invoices.modal.subtotal': 'Subtotal',
      'invoices.modal.tax': 'Tax',
      'invoices.modal.total': 'Total',
      'invoices.modal.invoice_item': 'Invoice item',
      'invoices.modal.save_draft': 'Save draft',
      'invoices.modal.save_send': 'Save & send',
      'invoices.modal.update_invoice': 'Update invoice',
      'invoices.modal.cancel': 'Cancel',
    // Settings
    'settings.company_updated': 'Company updated successfully',
    'settings.company_update_error': 'Failed to update company',
    'settings.switched_to': 'Switched to',
    'settings.switch_error': 'Failed to switch company',
    'settings.workspace_created': 'New workspace created successfully',
    'settings.workspace_create_error': 'Failed to create workspace',
    'settings.payments_load_connections_error': 'Failed to load payment ingestion connections',
    'settings.payments_load_events_error': 'Failed to load ingestion events',
    'settings.workspace_delete_active_error': 'You cannot delete the current active workspace.',
    'settings.workspace_deleted': 'Workspace deleted successfully:',
    'settings.workspace_delete_error': 'Failed to delete workspace',
    'settings.identifier_required': 'Identifier is required',
    'settings.connection_added': 'Payment ingestion connection added',
    'settings.connection_create_error': 'Failed to create payment ingestion connection',
    'settings.connection_deleted': 'Connection deleted',
    'settings.connection_delete_error': 'Failed to delete connection',
    'settings.loading': 'Loading...',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences and settings',
    'settings.tab_company': 'Company Profile',
    'settings.tab_profile': 'Profile',
    'settings.tab_security': 'Security',
    'settings.tab_branding': 'Branding',
    'settings.tab_workspaces': 'Workspaces',
    'settings.tab_payments': 'Payment Alerts',
    'settings.company_name': 'Company Name',
    'settings.industry': 'Industry',
    'settings.default_currency': 'Default Currency',
    'settings.tax_rate': 'Tax Rate (%)',
    'settings.usd_exchange_rate': 'USD Exchange Rate',
    'settings.save_changes': 'Save Changes',
    'settings.profile_title': 'Your Profile',
    'settings.profile_subtitle': 'These details reflect your user account.',
    'settings.workspaces_title': 'Switch Company Workspace',
    'settings.workspaces_subtitle': 'Use one email across multiple companies and choose which workspace to manage in this session.',
    'settings.create_workspace': 'Create New Workspace',
    'settings.no_workspaces': 'No workspaces found for this email.',
    'settings.workspace_role': 'Role',
    'settings.workspace_current': 'Current',
    'settings.workspace_switching': 'Switching...',
    'settings.workspace_switch': 'Switch',
    'settings.workspace_delete_disabled': 'Cannot delete current workspace',
    'settings.workspace_delete': 'Delete workspace',
    'settings.workspace_deleting': 'Deleting...',
    'settings.workspace_cannot_delete': 'Cannot Delete',
    'settings.payments_connect_title': 'Connect Mailbox',
    'settings.payments_connect_subtitle': 'Add a mailbox address to enable payment alert ingestion.',
    'settings.payments_placeholder_gmail': 'alerts@yourcompany.com',
    'settings.payments_display_name': 'Display name (optional)',
    'settings.payments_saving': 'Saving...',
    'settings.payments_add_connection': 'Add Connection',
    'settings.payments_connected': 'Connected Sources',
    'settings.payments_refreshing': 'Refreshing...',
    'settings.payments_refresh': 'Refresh',
    'settings.payments_loading_connections': 'Loading connections...',
    'settings.payments_none': 'No mailbox connections yet.',
    'settings.payments_removing': 'Removing...',
    'settings.payments_remove': 'Remove',
    'settings.payments_events_title': 'Recent Ingestion Events',
    'settings.payments_loading_events': 'Loading events...',
    'settings.payments_no_events': 'No ingestion events yet.',
    'settings.payments_subject': 'Subject',
    'settings.payments_error': 'Error',
    'settings.create_workspace_title': 'Create New Workspace',
    'settings.workspace_company_name': 'Company name',
    'settings.workspace_owner_email': 'Workspace owner email',
    'settings.workspace_owner_hint': 'Uses your current logged-in email',
    'settings.workspace_creating': 'Creating...',
    'settings.save_title': 'Save Changes',
    'settings.save_message': 'Are you sure you want to save these changes to your company profile?',
    'settings.delete_workspace_title': 'Delete Workspace',
    'settings.delete_workspace_message': 'Are you sure you want to delete',
    'settings.this_workspace': 'this workspace',
    'settings.delete_workspace_warning': 'This will permanently remove all its data and cannot be undone.',
    'settings.delete_workspace_confirm': 'Delete Workspace',
  },
  fr: {
    // Sidebar
    'nav.dashboard': 'Tableau de bord',
    'nav.clients': 'Clients',
    'nav.invoices': 'Factures',
    'nav.transactions': 'Transactions',
    'nav.expenses': 'Dépenses',
    'nav.reports': 'Rapports',
    'nav.team': 'Équipe',
    'nav.settings': 'Paramètres',
    // Topbar
    'topbar.welcome': 'Bon retour',
    'topbar.managing': 'Gestion de',
    'topbar.default_subtitle': 'Gérez vos finances efficacement',
    'topbar.search_placeholder': 'Rechercher des pages, fonctionnalités ou enregistrements...',
    'topbar.profile': 'Profil & Paramètres',
    'topbar.signout': 'Se déconnecter',
    'topbar.notifications': 'Notifications',
    'topbar.unread': 'non lues',
    'topbar.no_notifications': 'Aucune notification non lue',
    'topbar.caught_up': 'Vous êtes à jour',
    'topbar.loading_notifications': 'Chargement des notifications...',
    // Common
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.download_pdf': 'Télécharger le PDF',
    'common.na': 'N/D',
      'common.actions': 'Actions',
      'common.view': 'Voir',
      'common.edit': 'Modifier',
      'common.back': 'Retour',
      'common.save_and_send': 'Enregistrer et envoyer',
      'common.client': 'Client',
    'common.clear_filter': 'Effacer le filtre',
    'common.filtered_showing': 'Filtré : affichage',
    'common.unknown_error': 'Erreur inconnue',
    'common.your_company': 'Votre entreprise',
    // Status
    'status.paid': 'Payé',
    'status.in_progress': 'En attente',
    'status.overdue': 'En retard',
    'status.draft': 'Brouillon',
    'status.cancelled': 'Annulé',
    'status.pending': 'En attente',
    'status.sent': 'Envoyé',
    // Dashboard
    'dashboard.loading': 'Chargement du tableau de bord...',
    'dashboard.overview': 'Aperçu',
    'dashboard.greeting_morning': 'Bonjour',
    'dashboard.greeting_afternoon': 'Bon après-midi',
    'dashboard.greeting_evening': 'Bonsoir',
    'dashboard.greeting_night': 'Bonne nuit',
    'dashboard.subtitle': 'Voici la performance de votre entreprise aujourd’hui.',
    'dashboard.export_summary_pdf': 'Exporter le récapitulatif PDF',
    'dashboard.create_invoice': 'Créer une facture',
    'dashboard.income': 'Revenus',
    'dashboard.expenses': 'Dépenses',
    'dashboard.margin': 'marge',
    'dashboard.spend_vs_revenue': 'dépenses vs revenus',
    'dashboard.pending_amount': 'Montant en attente',
    'dashboard.outstanding_unpaid': 'En attente sur les factures impayées',
    'dashboard.profit': 'Bénéfice',
    'dashboard.invoices_tracked': 'factures suivies ce cycle',
    'dashboard.cancelled': 'annulées',
    'dashboard.cashflow_trends': 'Tendances de trésorerie',
    'dashboard.last_6_months': '6 derniers mois de revenus, dépenses, montants en attente et brouillons.',
    'dashboard.invoice_health': 'Santé des factures',
    'dashboard.invoice_health_subtitle': 'Répartition actuelle des statuts de factures.',
    'dashboard.no_data': 'Aucune donnée',
    'dashboard.latest_invoices': 'Dernières factures',
    'dashboard.view_all': 'Voir tout',
    'dashboard.no_invoices': 'Aucune facture pour le moment. Créez votre première facture pour suivre les encaissements.',
    'dashboard.client_label': 'Client',
    'dashboard.income_vs_expenses': 'Revenus vs dépenses',
    'dashboard.recent_period': 'Période récente',
    'dashboard.transactions_feed': 'Flux des transactions',
    'dashboard.latest_activity': 'Dernière activité',
    'dashboard.no_transactions': 'Aucune transaction récente à afficher.',
    'dashboard.add_new_client': 'Ajouter un client',
    'dashboard.add_new_client_desc': 'Créez et organisez les profils clients.',
    'dashboard.create_invoice_desc': 'Générez et partagez des factures rapidement.',
    'dashboard.add_expense': 'Ajouter une dépense',
    'dashboard.add_expense_desc': 'Tenez les dépenses à jour.',
    'dashboard.summary_pdf_title': 'Générer le récapitulatif PDF',
    'dashboard.summary_pdf_message': 'Cela générera et téléchargera un PDF récapitulatif complet. Cela peut prendre quelques secondes.',
    'dashboard.download_pdf': 'Télécharger le PDF',
    'dashboard.summary_pdf_error': 'Impossible de télécharger le PDF récapitulatif',
    'dashboard.client_invoice': 'Facture client',
    'dashboard.expense_title': 'Dépense',
    'dashboard.operational_expense': 'Dépense opérationnelle',
    'dashboard.collected': 'Encaissements',    // Search
    'search.title': 'Recherche',
    'search.results_for': 'Résultats pour',
    'search.type_hint': 'Tapez dans la barre du haut pour rechercher',
    'search.helper': 'Recherchez dans les pages, clients, factures et dépenses depuis la barre de navigation.',
    'search.loading': 'Recherche en cours...',
    'search.error': 'Impossible de charger la recherche. Veuillez réessayer.',
    'search.no_matches': 'Aucun résultat trouvé dans les pages, clients, factures ou dépenses.',
    'search.pages': 'Pages',
    'search.clients': 'Clients',
    'search.invoices': 'Factures',
    'search.expenses': 'Dépenses',
    'search.no_contact': 'Aucun contact',
    'search.client_unavailable': 'Client indisponible',
    'search.due': 'Échéance',
    'search.unnamed_supplier': 'Fournisseur sans nom',
    'search.uncategorized': 'Non catégorisé',
    'search.nav_dashboard_desc': 'Vue d’ensemble des performances et actions rapides.',
    'search.nav_workspace': 'Espace de travail',
    'search.nav_clients_desc': 'Gérez les clients, contacts et historiques de compte.',
    'search.nav_crm': 'CRM',
    'search.nav_invoices_desc': 'Créez des factures et suivez les paiements.',
    'search.nav_billing': 'Facturation',
    'search.nav_expenses_desc': 'Suivez les dépenses, catégories et fournisseurs.',
    'search.nav_finance': 'Finance',
    'search.nav_reports_desc': 'Analysez revenus, coûts et rentabilité.',
    'search.nav_analytics': 'Analytique',
    'search.nav_team_desc': 'Invitez et gérez l’équipe et les rôles.',
    'search.nav_admin': 'Administration',
    'search.nav_settings_desc': 'Configurez le profil, la marque et les préférences.',
    // Reports
    'reports.title': 'Rapports financiers',
    'reports.export_pdf': 'Exporter PDF',
    'reports.export_csv': 'Exporter CSV',
    'reports.filter_title': 'Filtrer les rapports',
    'reports.start_date': 'Date de début',
    'reports.end_date': 'Date de fin',
    'reports.generate_report': 'Générer le rapport',
    'reports.loading': 'Chargement...',
    'reports.total_revenue': 'Revenus totaux',
    'reports.total_expenses': 'Dépenses totales',
    'reports.net_profit': 'Bénéfice net',
    'reports.margin': 'Marge',
    'reports.net_cashflow': 'Tendance du flux net',
    'reports.collected_minus_expenses': 'Encaissements - Dépenses',
    'reports.no_trend': 'Aucune donnée de tendance pour la période sélectionnée',
    'reports.top_expense_categories': 'Principales catégories de dépenses',
    'reports.highest_spend': 'Catégories les plus coûteuses',
    'reports.no_expense_categories': 'Aucune catégorie de dépense pour la période sélectionnée',
    'reports.invoices_summary': 'Résumé des factures',
    'reports.total_paid': 'Total payé',
    'reports.total_pending': 'Total en attente',
    'reports.collected': 'Encaissements',
    'reports.total_invoices': 'Total des factures',
    'reports.expenses_summary': 'Résumé des dépenses',
    'reports.total_records': 'Total des enregistrements',
    'reports.client_performance': 'Performance client',
    'reports.view_all': 'Voir tout',
    'reports.show_less': 'Voir moins',
    'reports.loading_performance': 'Chargement des performances...',
    'reports.performance_error': 'Impossible de charger les performances',
    'reports.collection_rate': 'Taux de recouvrement',
    'reports.paid_rate': 'Taux payé',
    'reports.score': 'Score',
    'reports.empty_prompt': 'Sélectionnez une période et cliquez sur "Générer le rapport" pour voir les données financières',
    'reports.ai_forecast_title': 'Prévision assistée par IA',
    'reports.ai_forecast_desc': 'Cliquez sur le bouton ci-dessous pour générer une prévision de trésorerie à 90 jours basée sur vos données historiques. Cette fonctionnalité utilise l’IA pour prédire les tendances financières.',
    'reports.generate_forecast': 'Générer la prévision 90 jours',
    'reports.generating_forecast': 'Génération de la prévision...',
    'reports.ai_loading': 'L’IA analyse vos données...',
    'reports.pdf_title': 'Rapport financier FiinFlow',
    'reports.pdf_period': 'Période',
    'reports.pdf_all_time': 'Tout le temps',
    'reports.pdf_present': 'Présent',
    'reports.pdf_summary_title': 'Résumé financier',
    'reports.pdf_metric': 'Indicateur',
    'reports.pdf_value': 'Valeur',
    'reports.pdf_invoices': 'Factures',
    'reports.pdf_expenses': 'Dépenses',
    'reports.pdf_invoice_number': 'Facture #',
    'reports.pdf_client': 'Client',
    'reports.pdf_amount': 'Montant',
    'reports.pdf_status': 'Statut',
    'reports.pdf_due_date': 'Date d’échéance',
    'reports.pdf_supplier': 'Fournisseur',
    'reports.pdf_category': 'Catégorie',
    'reports.pdf_date': 'Date',
    'reports.csv_summary': 'RÉSUMÉ FINANCIER',
    'reports.csv_invoices': 'FACTURES',
    'reports.csv_expenses': 'DÉPENSES',
    'reports.csv_period': 'Période',
    // Common (extended)
    'common.save': 'Enregistrer',
    'common.name': 'Nom',
    'common.email': 'E-mail',
    'common.phone': 'Téléphone',
    'common.address': 'Adresse',
    'common.status': 'Statut',
    'common.role': 'Rôle',
    // Login
    'login.back_home': "Retour à l'accueil",
    'login.title': 'Connectez-vous à votre compte',
    'login.subtitle': "Utilisez vos identifiants d'espace de travail pour continuer.",
    'login.email_label': 'Adresse e-mail',
    'login.email_placeholder': 'vous@entreprise.com',
    'login.password_label': 'Mot de passe',
    'login.password_placeholder': 'Saisissez votre mot de passe',
    'login.remember': 'Se souvenir de moi',
    'login.forgot': 'Mot de passe oublié ?',
    'login.signing_in': 'Connexion...',
    'login.sign_in': 'Se connecter',
    'login.no_account': "Vous n'avez pas de compte ?",
    'login.start_setup': 'Démarrer une configuration',
    'login.success': 'Connexion réussie',
    'login.error_default': 'Échec de la connexion. Veuillez vérifier vos identifiants.',
    // Not Found
    'notfound.code': 'Erreur 404',
    'notfound.title': 'Page introuvable',
    'notfound.subtitle': 'La page demandée n’existe pas ou a été déplacée.',
    'notfound.back': 'Retour',
    'notfound.to_dashboard': 'Aller au tableau de bord',
    'notfound.to_home': "Aller à l'accueil",
    // Password rules
    'password.rule.min_length': 'Au moins 8 caractères',
    'password.rule.uppercase': 'Au moins une lettre majuscule',
    'password.rule.lowercase': 'Au moins une lettre minuscule',
    'password.rule.number': 'Au moins un chiffre',
    'password.rule.special': 'Au moins un caractère spécial',
    'password.error_strong': 'Le mot de passe doit être fort : 8+ caractères, majuscule, minuscule, chiffre et caractère spécial.',
    // Change Password
    'change_password.title': 'Changer le mot de passe',
    'change_password.current_label': 'Mot de passe actuel',
    'change_password.new_label': 'Nouveau mot de passe',
    'change_password.confirm_label': 'Confirmer le nouveau mot de passe',
    'change_password.mismatch': 'Les nouveaux mots de passe ne correspondent pas',
    'change_password.success': 'Mot de passe modifié avec succès !',
    'change_password.success_toast': 'Mot de passe modifié avec succès',
    'change_password.error_default': 'Échec de la modification du mot de passe',
    'change_password.changing': 'Modification...',
    'change_password.submit': 'Changer le mot de passe',
    // Forgot Password
    'forgot_password.toast_sent': 'Si le compte existe, un e-mail de réinitialisation a été envoyé.',
    'forgot_password.success_title': 'Vérifiez votre e-mail',
    'forgot_password.success_body': "Si un compte existe avec cette adresse e-mail, vous recevrez des instructions de réinitialisation du mot de passe.",
    'forgot_password.success_hint': 'Veuillez vérifier votre boîte de réception et votre dossier spam.',
    'forgot_password.back_login': 'Retour à la connexion',
    'forgot_password.title': 'Mot de passe oublié ?',
    'forgot_password.subtitle': "Saisissez votre adresse e-mail et nous vous enverrons un lien de réinitialisation.",
    'forgot_password.email_label': 'Adresse e-mail',
    'forgot_password.email_placeholder': 'votre@email.com',
    'forgot_password.sending': 'Envoi...',
    'forgot_password.send_link': 'Envoyer le lien de réinitialisation',
    'forgot_password.remember_prompt': 'Vous vous souvenez de votre mot de passe ?',
    'forgot_password.sign_in': 'Se connecter',
    'forgot_password.general_login': 'Aller à la connexion générale',
    // Reset Password
    'reset_password.invalid_link_error': 'Lien de réinitialisation invalide ou manquant',
    'reset_password.mismatch': 'Les mots de passe ne correspondent pas',
    'reset_password.success_toast': 'Mot de passe réinitialisé avec succès',
    'reset_password.error_default': 'Échec de la réinitialisation du mot de passe. Le lien a peut-être expiré. Veuillez demander un nouveau lien.',
    'reset_password.invalid_title': 'Lien invalide',
    'reset_password.invalid_body': 'Ce lien de réinitialisation est invalide ou a expiré.',
    'reset_password.request_new_link': 'Demander un nouveau lien',
    'reset_password.success_title': 'Mot de passe réinitialisé avec succès !',
    'reset_password.success_body': 'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    'reset_password.redirecting': 'Redirection vers la page de connexion...',
    'reset_password.title': 'Réinitialiser le mot de passe',
    'reset_password.subtitle': 'Saisissez votre nouveau mot de passe ci-dessous',
    'reset_password.new_label': 'Nouveau mot de passe',
    'reset_password.new_placeholder': 'Saisissez le nouveau mot de passe',
    'reset_password.hide': 'Masquer',
    'reset_password.show': 'Afficher',
    'reset_password.confirm_label': 'Confirmer le nouveau mot de passe',
    'reset_password.confirm_placeholder': 'Confirmez le nouveau mot de passe',
    'reset_password.resetting': 'Réinitialisation...',
    'reset_password.submit': 'Réinitialiser le mot de passe',
    'reset_password.remember_prompt': 'Vous vous souvenez de votre mot de passe ?',
    'reset_password.sign_in': 'Se connecter',
    // Set Password
    'set_password.invalid_link_error': "Lien d'invitation invalide ou manquant",
    'set_password.mismatch': 'Les mots de passe ne correspondent pas',
    'set_password.success_toast': 'Mot de passe défini avec succès',
    'set_password.error_default': "Échec de la définition du mot de passe. Veuillez réessayer ou demander une nouvelle invitation.",
    'set_password.invalid_title': 'Lien invalide',
    'set_password.invalid_body': "Ce lien d'invitation est invalide ou a expiré. Veuillez contacter votre administrateur pour une nouvelle invitation.",
    'set_password.go_login': 'Aller à la connexion',
    'set_password.success_title': 'Mot de passe défini avec succès !',
    'set_password.success_body': "Votre mot de passe a été défini. Vous pouvez maintenant vous connecter à votre espace.",
    'set_password.redirecting': 'Redirection vers la page de connexion...',
    'set_password.welcome': 'Bienvenue !',
    'set_password.subtitle': 'Définissez votre mot de passe pour rejoindre FiinFlow',
    'set_password.title': 'Définir votre mot de passe',
    'set_password.password_label': 'Mot de passe',
    'set_password.password_placeholder': 'Saisissez votre mot de passe',
    'set_password.confirm_label': 'Confirmer le mot de passe',
    'set_password.confirm_placeholder': 'Confirmez votre mot de passe',
    'set_password.hide': 'Masquer',
    'set_password.show': 'Afficher',
    'set_password.setting': 'Définition du mot de passe...',
    'set_password.submit': 'Définir le mot de passe et continuer',
    'set_password.already_prompt': 'Vous avez déjà un compte ?',
    'set_password.sign_in': 'Se connecter',
    // Company Setup
    'company_setup.consent_required': 'Veuillez accepter le consentement de participation à la recherche avant de continuer.',
    'company_setup.success_toast': 'Entreprise créée avec succès. Vous pouvez maintenant vous connecter.',
    'company_setup.error_default': "Échec de la création de l'entreprise",
    'company_setup.back_home': "Retour à l'accueil",
    'company_setup.title': 'Créez votre espace de travail',
    'company_setup.subtitle': "Configurez le compte de votre entreprise pour commencer.",
    'company_setup.name_label': "Nom de l'entreprise",
    'company_setup.name_placeholder': "Nom de l'entreprise",
    'company_setup.email_label': "E-mail de l'entreprise",
    'company_setup.email_placeholder': 'entreprise@email.com',
    'company_setup.phone_label': 'Numéro de téléphone',
    'company_setup.phone_placeholder': '+250 XXX XXX XXX',
    'company_setup.industry_label': 'Secteur (optionnel)',
    'company_setup.industry_placeholder': 'Secteur',
    'company_setup.address_label': "Adresse de l'entreprise",
    'company_setup.address_placeholder': "Adresse de l'entreprise",
    'company_setup.password_label': 'Créer un mot de passe',
    'company_setup.password_placeholder': 'Créez un mot de passe fort',
    'company_setup.confirm_label': 'Confirmer le mot de passe',
    'company_setup.confirm_placeholder': 'Saisissez de nouveau le mot de passe',
    'company_setup.password_mismatch': 'Les mots de passe ne correspondent pas.',
    'company_setup.consent_blurb': "FiinFlow fait partie d'un projet de fin d'études à l'African Leadership University. Les données sont utilisées à des fins académiques et supprimées après l'étude pilote.",
    'company_setup.consent_label': 'Je consens à participer au pilote de recherche FiinFlow.',
    'company_setup.consent_link': 'Lire les informations complètes de consentement',
    'company_setup.creating': 'Création...',
    'company_setup.submit': 'Créer un compte',
    'company_setup.already_prompt': 'Vous avez déjà un compte ?',
    'company_setup.sign_in': 'Se connecter',
    // User Setup
    'user_setup.success_toast': "Utilisateur administrateur créé avec succès",
    'user_setup.error_default': "Échec de la création de l'administrateur",
    'user_setup.title': "Créer l'administrateur",
    'user_setup.subtitle': 'Configurer le compte administrateur principal',
    'user_setup.name_label': 'Nom complet *',
    'user_setup.name_placeholder': 'Jean Dupont',
    'user_setup.email_label': 'E-mail *',
    'user_setup.email_placeholder': 'admin@entreprise.com',
    'user_setup.phone_label': 'Téléphone (optionnel)',
    'user_setup.phone_placeholder': '+250 XXX XXX XXX',
    'user_setup.role_label': 'Rôle :',
    'user_setup.role_value': 'Administrateur (accès complet)',
    'user_setup.creating': 'Création...',
    'user_setup.submit': "Créer l'administrateur et continuer",
    // Research Consent
    'research_consent.org': 'African Leadership University',
    'research_consent.title': 'Informations de consentement à la recherche',
    'research_consent.about_title': "À propos de l'étude",
    'research_consent.about_body': "FiinFlow est un projet de fin d'études développé à l'African Leadership University (ALU). Cette étude pilote évalue si FiinFlow peut aider les petites et moyennes entreprises (PME) au Rwanda à gérer leurs finances plus efficacement. Votre participation nous aide à comprendre l'utilisabilité réelle et à améliorer le système.",
    'research_consent.data_title': 'Données collectées',
    'research_consent.data_company_label': "Informations sur l'entreprise :",
    'research_consent.data_company_body': "Nom de l'entreprise, e-mail, téléphone et adresse (fournis lors de l'inscription).",
    'research_consent.data_financial_label': 'Dossiers financiers :',
    'research_consent.data_financial_body': 'Factures, dépenses et informations clients que vous saisissez dans le système.',
    'research_consent.data_usage_label': "Données d'utilisation :",
    'research_consent.data_usage_body': "Fonctionnalités utilisées et fréquence, pour évaluer l'utilisabilité du système.",
    'research_consent.protect_title': 'Comment nous protégeons vos données',
    'research_consent.protect_item_1': 'Tous les mots de passe sont hachés avec bcrypt et jamais stockés en clair.',
    'research_consent.protect_item_2': "Les données de votre entreprise sont isolées des autres entreprises via l'authentification par jeton.",
    'research_consent.protect_item_3': "Le contrôle d'accès basé sur les rôles garantit que seuls les membres autorisés voient les données sensibles.",
    'research_consent.protect_item_4': "Les données seront stockées de manière sécurisée et supprimées après la fin de l'étude pilote.",
    'research_consent.rights_title': 'Vos droits en tant que participant',
    'research_consent.rights_item_1': "La participation est totalement volontaire. Vous n'êtes pas obligé d'utiliser FiinFlow.",
    'research_consent.rights_item_2': 'Vous pouvez vous retirer à tout moment sans pénalité ni conséquence négative.',
    'research_consent.rights_item_3': 'Vous pouvez demander la suppression de vos données à tout moment pendant ou après l’étude.',
    'research_consent.rights_item_4': "Vous avez le droit de poser des questions sur l'étude à tout moment.",
    'research_consent.withdraw_title': 'Comment se retirer',
    'research_consent.withdraw_body': "Pour vous retirer de l'étude, il suffit d'arrêter d'utiliser FiinFlow et de contacter la chercheuse. Toutes vos données seront supprimées définitivement du système dans les 7 jours suivant votre demande. Il n'y a aucune pénalité pour le retrait.",
    'research_consent.contact_title': 'Contacter la chercheuse',
    'research_consent.contact_intro': 'Si vous avez des questions concernant cette étude, veuillez contacter :',
    'research_consent.contact_name': 'Grace Munezero',
    'research_consent.contact_org': 'African Leadership University, Kigali, Rwanda',
    'research_consent.back_setup': "Retour à la configuration de l'entreprise",
    // Analytics
    'analytics.loading': 'Chargement des analyses...',
    'analytics.no_data': 'Aucune donnée analytique disponible',
    'analytics.income': 'Revenus',
    'analytics.expense': 'Dépenses',
    'analytics.title': 'Analyses',
    'analytics.subtitle': 'Visualisez vos dépenses et vos indicateurs financiers',
    'analytics.top_category': 'Catégorie principale',
    'analytics.total_income': 'Revenus totaux (YTD)',
    'analytics.total_expense': 'Dépenses totales (YTD)',
    'analytics.income_vs_expense': 'Revenus vs dépenses',
    'analytics.spending_by_category': 'Dépenses par catégorie',
    'analytics.summary': 'Résumé',
    'analytics.savings_rate': 'Taux d’épargne',
    'analytics.avg_expense': 'Dépense mensuelle moyenne',
    'analytics.avg_income': 'Revenu mensuel moyen',
    // Team
    'team.loading': "Chargement de l'équipe...",
    'team.title': "Membres de l'équipe",
    'team.subtitle': "Gérez les utilisateurs qui ont accès à l'espace de travail de l'entreprise",
    'team.invite_user': '+ Inviter un utilisateur',
    'team.add_member': '+ Ajouter un membre',
    'team.role_label': 'Rôle',
    'team.joined_label': 'Rejoint',
    'team.resend_invite': "Renvoyer l'invitation",
    'team.cancel_invite': "Annuler l'invitation",
    'team.edit_member': 'Modifier le membre',
    'team.remove_member': 'Supprimer le membre',
    'team.table_name': 'Nom',
    'team.table_email': 'E-mail',
    'team.table_phone': 'Téléphone',
    'team.table_role': 'Rôle',
    'team.table_status': 'Statut',
    'team.table_joined': 'Rejoint',
    'team.empty_title': "Aucun membre pour l'instant",
    'team.empty_subtitle': "Invitez ou ajoutez des membres pour collaborer",
    'team.add_team_member': '+ Ajouter un membre',
    'team.edit_title': 'Modifier un membre',
    'team.add_title': 'Ajouter un membre',
    'team.name_label': 'Nom *',
    'team.name_placeholder': 'Jean Dupont',
    'team.email_label': 'E-mail *',
    'team.email_placeholder': 'jean@example.com',
    'team.password_edit_label': 'Mot de passe (laisser vide pour conserver)',
    'team.password_new_label': 'Mot de passe *',
    'team.password_edit_placeholder': 'Nouveau mot de passe',
    'team.password_new_placeholder': 'Créez un mot de passe fort',
    'team.phone_label': 'Téléphone',
    'team.phone_placeholder': '+250 XXX XXX XXX',
    'team.role_staff_desc': 'Personnel - Peut seulement créer des brouillons',
    'team.role_finance_manager_desc': 'Responsable finance - Accès complet factures/dépenses',
    'team.role_admin_desc': 'Admin - Accès complet au système',
    'team.role_super_admin_desc': 'Super Admin - Accès global au système',
    'team.update': 'Mettre à jour',
    'team.invite_title': "Inviter un utilisateur",
    'team.invite_subtitle': "Envoyez un e-mail d'invitation à un nouvel utilisateur. Il recevra un lien pour définir son mot de passe et rejoindre votre espace.",
    'team.invite_note': "L'utilisateur recevra un e-mail avec un lien sécurisé pour définir son mot de passe. Le lien est valable 7 jours.",
    'team.send_invite': "Envoyer l'invitation",
    'team.remove_title': 'Supprimer le membre',
    'team.remove_message': "Voulez-vous vraiment supprimer ce membre ? Il perdra l'accès à cet espace.",
    'team.remove_confirm': 'Supprimer',
    'team.role_super_admin': 'Super Admin',
    'team.role_admin': 'Admin',
    'team.role_finance_manager': 'Responsable finance',
    'team.role_staff': 'Personnel',
    'team.status_pending': 'En attente',
    'team.status_active': 'Actif',
    'team.status_suspended': 'Suspendu',
    'team.updated_success': "Membre mis à jour avec succès",
    'team.created_success': "Membre ajouté avec succès",
    'team.save_error': "Échec de l'enregistrement du membre. Veuillez réessayer.",
    'team.removed_success': "Membre supprimé avec succès",
    'team.delete_error': "Échec de la suppression du membre",
    'team.invite_success': "Utilisateur invité avec succès. E-mail envoyé.",
    'team.invite_error': "Échec de l'invitation. Veuillez réessayer.",
    'team.resend_success': "Invitation renvoyée avec succès",
    'team.resend_error': "Échec du renvoi de l'invitation. Veuillez réessayer.",
    // Clients
    'clients.phone_validation': 'Le numéro de téléphone doit contenir au moins 10 chiffres.',
    'clients.updated_success': 'Client mis à jour avec succès',
    'clients.created_success': 'Client créé avec succès',
    'clients.save_error': "Échec de l'enregistrement du client. Veuillez réessayer.",
    'clients.deleted_success': 'Client supprimé avec succès',
    'clients.delete_error': 'Échec de la suppression du client',
    'clients.loading': 'Chargement des clients...',
    'clients.title': 'Clients',
    'clients.add_client': '+ Ajouter un client',
    'clients.empty_title': "Aucun client pour l'instant",
    'clients.empty_subtitle': 'Ajoutez votre premier client pour commencer à créer des factures',
    'clients.email_label': 'E-mail',
    'clients.phone_label': 'Téléphone',
    'clients.view_client': 'Voir le client',
    'clients.edit_client': 'Modifier le client',
    'clients.delete_client': 'Supprimer le client',
    'clients.table_name': 'Nom',
    'clients.table_contact': 'Contact',
    'clients.table_email': 'E-mail',
    'clients.table_phone': 'Téléphone',
    'clients.edit_title': 'Modifier le client',
    'clients.add_title': 'Ajouter un client',
    'clients.form_company_name': "Nom de l'entreprise *",
    'clients.form_contact': 'Contact *',
    'clients.form_email': 'E-mail *',
    'clients.form_phone': 'Téléphone *',
    'clients.form_address': 'Adresse *',
    'clients.update': 'Mettre à jour',
    'clients.create': 'Créer',
      'clients.delete_title': 'Supprimer le client',
      'clients.delete_message': 'Voulez-vous vraiment supprimer ce client ? Cette action est irréversible.',
      // Client Detail
      'client_detail.loading': 'Chargement du client...',
      'client_detail.not_found': 'Client introuvable',
      'client_detail.back_clients': 'Retour aux clients',
      'client_detail.client_since': 'Client depuis',
      'client_detail.revenue': 'Revenus',
      'client_detail.expenses': 'Dépenses',
      'client_detail.profit': 'Profit',
      'client_detail.net_profit': 'Profit net',
      'client_detail.payment_rate': 'Taux de paiement',
      'client_detail.currency_label': 'Devise',
      'client_detail.paid_invoices': 'factures payées',
      'client_detail.records': 'enregistrements',
      'client_detail.revenue_minus_expenses': 'revenus - dépenses',
      'client_detail.of': 'sur',
      'client_detail.paid': 'payées',
      'client_detail.invoice_status_breakdown': 'Répartition des statuts de facture',
      'client_detail.invoices_label': 'factures',
      'client_detail.invoice_label': 'facture',
      'client_detail.revenue_vs_expenses': 'Revenus vs dépenses',
      'client_detail.contact_info': 'Informations de contact',
      'client_detail.contact_person': 'Personne de contact',
      'client_detail.quick_stats': 'Statistiques rapides',
      'client_detail.total_invoices': 'Total des factures',
      'client_detail.paid_invoices_label': 'Factures payées',
      'client_detail.unpaid_invoices': 'Factures impayées',
      'client_detail.linked_expenses': 'Dépenses liées',
      'client_detail.tab_invoices': 'Factures',
      'client_detail.tab_expenses': 'Dépenses',
      'client_detail.no_invoices': 'Aucune facture pour ce client',
      'client_detail.no_expenses': 'Aucune dépense pour ce client',
      'client_detail.invoice_number': 'Facture #',
      'client_detail.amount': 'Montant',
      'client_detail.due_date': "Date d'échéance",
      'client_detail.status': 'Statut',
      'client_detail.supplier': 'Fournisseur',
      'client_detail.category': 'Catégorie',
      'client_detail.total': 'Total',
      'client_detail.remaining': 'Restant',
      'client_detail.view_all': 'Voir tout',
      'client_detail.show_less': 'Voir moins',
    // Transactions
    'transactions.title': 'Transactions',
    'transactions.tab_all': 'Toutes',
    'transactions.tab_income': 'Revenus',
    'transactions.tab_expenses': 'Dépenses',
    'transactions.search_placeholder': 'Rechercher des transactions...',
    'transactions.date': 'Date',
    'transactions.name': 'Nom',
    'transactions.type': 'Type',
    'transactions.spent': 'Dépensé',
    'transactions.received': 'Reçu',
    'transactions.action': 'Action',
    'transactions.linked': 'Liée',
    'transactions.unlink': 'Délier',
    'transactions.link': 'Lier',
    'transactions.invoice': 'Facture',
    'transactions.expense': 'Dépense',
    'transactions.already_linked': 'Cette transaction est déjà liée.',
    'transactions.clear_filters': 'Effacer les filtres',
    'transactions.empty_title': 'Aucune transaction',
    'transactions.empty_subtitle': 'Les transactions apparaîtront ici une fois enregistrées.',
    'transactions.empty_subtitle_filtered': 'Aucune transaction ne correspond à vos filtres.',
    'transactions.load_more': 'Charger plus',
    'transactions.loading': 'Chargement des transactions...',
      'transactions.delete_title': 'Supprimer la transaction',
      'transactions.delete_message': 'Voulez-vous vraiment supprimer cette transaction ?',
      'transactions.delete_soon': 'La suppression sera disponible bientôt',
      'transactions.fallback_expense': 'Dépense',
      'transactions.fallback_client': 'Client',
    // Expenses (table + header)
    'expenses.title': 'Dépenses',
    'expenses.export_pdf': 'Exporter PDF',
    'expenses.add': '+ Ajouter une dépense',
    'expenses.filtered_showing': 'Filtré : affichage',
    'expenses.table.supplier': 'Fournisseur',
    'expenses.table.category': 'Catégorie',
    'expenses.table.created_at': 'Créé le',
    'expenses.table.total_amount': 'Montant total',
    'expenses.table.amount_paid': 'Montant payé',
    'expenses.table.remaining': 'Restant',
      'expenses.table.due_date': 'Date d’échéance',
      'expenses.table.status': 'Statut',
      'expenses.table.actions': 'Actions',
      'expenses.clear_filter': 'Effacer le filtre',
      'expenses.empty_title': "Aucune dépense pour l'instant",
      'expenses.empty_subtitle': 'Ajoutez votre première dépense pour suivre vos coûts',
      'expenses.loading': 'Chargement des dépenses...',
      'expenses.created_success': 'Dépense créée avec succès',
      'expenses.create_failed': "Échec de la création de la dépense",
      'expenses.deleted_success': 'Dépense supprimée avec succès',
      'expenses.delete_failed': "Échec de la suppression de la dépense",
      'expenses.form_invalid_total': 'Veuillez saisir un montant total valide.',
      'expenses.form_negative_paid': 'Le montant payé ne peut pas être négatif.',
      'expenses.form_paid_exceeds': 'Le montant payé ne peut pas dépasser le montant total.',
      'expenses.form_supplier_required': 'Le fournisseur est obligatoire.',
      'expenses.receipt_open_failed': "Échec de l'ouverture du reçu.",
      'expenses.pdf_downloaded': 'Rapport des dépenses téléchargé.',
      'expenses.pdf_failed': 'Échec du téléchargement du rapport des dépenses.',
      'expenses.linked_success': 'Dépense liée avec succès.',
      'expenses.linked_updated': 'Montant lié appliqué. Restant :',
      'expenses.linked_failed_apply': "Échec de l'application du montant lié.",
      'expenses.mobile.total': 'Total',
      'expenses.mobile.paid': 'Payé',
      'expenses.mobile.remaining': 'Restant',
      'expenses.mobile.due_date': 'Échéance',
      'expenses.modal.create_title': 'Créer une dépense',
      'expenses.modal.linked_client': 'Client lié',
      'expenses.modal.no_linked_client': 'Aucun client lié',
      'expenses.modal.supplier_name_required': 'Nom du fournisseur *',
      'expenses.modal.supplier_name': 'Nom du fournisseur',
      'expenses.modal.category': 'Catégorie',
      'expenses.modal.custom_category_placeholder': 'Saisir une catégorie',
      'expenses.modal.total_amount': 'Montant total',
      'expenses.modal.amount_paid': 'Montant payé',
      'expenses.modal.remaining_amount': 'Montant restant',
      'expenses.modal.due_date': "Date d'échéance",
      'expenses.modal.payment_method': 'Mode de paiement',
      'expenses.modal.reference_number': 'Numéro de référence',
      'expenses.modal.reference_placeholder': 'Référence de transaction / reçu',
      'expenses.modal.description_notes': 'Description / notes',
      'expenses.modal.description_placeholder': 'Ajoutez des détails sur cette dépense...',
      'expenses.modal.receipt_optional': 'Reçu (optionnel)',
      'expenses.modal.upload_receipt': 'Téléverser le reçu',
      'expenses.modal.change_receipt': 'Changer le reçu',
      'expenses.modal.receipt_selected': 'Sélectionné :',
      'expenses.modal.receipt_accepted': 'PDF, JPG ou PNG acceptés',
      'expenses.modal.summary_title': 'Résumé',
      'expenses.modal.summary_total': 'Total',
      'expenses.modal.summary_paid': 'Payé',
      'expenses.modal.summary_remaining': 'Restant',
      'expenses.modal.tips_title': 'Conseils',
      'expenses.modal.tip_supplier': 'Utilisez un nom de fournisseur clair pour les rapports.',
      'expenses.modal.tip_reference': 'Ajoutez une référence pour le rapprochement bancaire.',
      'expenses.modal.tip_link_client': 'Liez à un client pour organiser les coûts.',
      'expenses.modal.cancel': 'Annuler',
      'expenses.modal.create_button': 'Créer la dépense',
      'expenses.confirm_delete_title': 'Supprimer la dépense',
      'expenses.confirm_delete_message': "Voulez-vous vraiment supprimer cette dépense ? Cette action est irréversible.",
      'expenses.confirm_delete_confirm': 'Supprimer',
      'expenses.confirm_delete_cancel': 'Annuler',
      'expenses.confirm_pdf_title': 'Télécharger le rapport des dépenses',
      'expenses.confirm_pdf_message': 'Générer et télécharger un rapport PDF des dépenses ?',
      'expenses.confirm_pdf_confirm': 'Télécharger le PDF',
      'expenses.confirm_pdf_cancel': 'Annuler',
      'expenses.confirm_link_title': 'Lier la dépense',
      'expenses.confirm_link_message_prefix': 'Lier la dépense',
      'expenses.confirm_link_message_suffix': 'à cette transaction ?',
      'expenses.confirm_link_confirm': 'Lier',
      'expenses.confirm_link_cancel': 'Annuler',
    // Invoices (table + header)
    'invoices.title': 'Factures',
    'invoices.create': 'Créer une facture',
    'invoices.table.number': 'Facture #',
    'invoices.table.client': 'Client',
    'invoices.table.amount': 'Montant',
    'invoices.table.paid': 'Payé',
    'invoices.table.remaining': 'Restant',
    'invoices.table.status': 'Statut',
    'invoices.table.created': 'Créé le',
      'invoices.table.due_date': 'Date d’échéance',
      'invoices.type.tax': 'Facture fiscale',
      'invoices.loading': 'Chargement des factures...',
      'invoices.empty_title': "Aucune facture pour l'instant",
      'invoices.empty_subtitle': 'Créez votre première facture pour suivre les paiements',
      'invoices.linked_success': 'Facture liée avec succès.',
      'invoices.linked_updated': 'Montant lié appliqué. Restant :',
      'invoices.linked_failed_apply': "Échec de l'application du montant lié.",
      'invoices.save_failed': "Échec de l'enregistrement de la facture",
      'invoices.save_send_failed': "Échec de l'enregistrement et de l'envoi de la facture",
      'invoices.saved_draft': 'Facture enregistrée comme brouillon',
      'invoices.saved_not_sent': 'Facture enregistrée mais non envoyée',
      'invoices.sent_email_sent': 'Facture envoyée et e-mail délivré',
      'invoices.sent_email_failed': "Facture envoyée mais échec de l'e-mail :",
      'invoices.sent_email_not_attempted': "Facture envoyée mais e-mail non tenté :",
      'invoices.updated_email_sent': 'Facture mise à jour et e-mail envoyé',
      'invoices.updated_email_failed': "Facture mise à jour mais échec de l'e-mail :",
      'invoices.updated_email_not_attempted': "Facture mise à jour mais e-mail non tenté :",
      'invoices.emailjs_missing_env': "Les paramètres d'e-mail sont manquants. Configurez les variables d'environnement EmailJS.",
      'invoices.no_recipient_email': 'Aucun e-mail de destinataire',
      'invoices.preview_title': 'Aperçu de la facture',
      'invoices.preview_subtitle': "Vérifiez avant l'envoi",
      'invoices.sending': 'Envoi...',
      'invoices.bill_to': 'Facturer à',
      'invoices.invoice_date': 'Date de facture',
      'invoices.due_date': "Date d'échéance",
      'invoices.qty': 'Qté',
      'invoices.description': 'Description',
      'invoices.unit_price': 'Prix unitaire',
      'invoices.amount': 'Montant',
      'invoices.subtotal': 'Sous-total',
      'invoices.sales_tax': 'Taxe',
      'invoices.total': 'Total',
      'invoices.how_to_pay': 'Comment payer',
      'invoices.pay_mobile_money': 'Payer via Mobile Money',
      'invoices.pay_bank_transfer': 'Virement bancaire',
      'invoices.pay_use_reference': 'Utiliser la référence',
      'invoices.label.standard': 'FACTURE STANDARD',
      'invoices.label.proforma': 'FACTURE PROFORMA',
      'invoices.label.tax': 'FACTURE FISCALE',
      'invoices.label.commercial': 'FACTURE COMMERCIALE',
      'invoices.label.credit_note': 'AVOIR',
      'invoices.label.debit_note': 'NOTE DE DEBIT',
      'invoices.type.standard': 'Standard',
      'invoices.type.proforma': 'Proforma',
      'invoices.type.commercial': 'Commerciale',
      'invoices.type.credit_note': 'Avoir',
      'invoices.type.debit_note': 'Note de débit',
      'invoices.confirm_delete_title': 'Supprimer la facture',
      'invoices.confirm_delete_message': "Voulez-vous vraiment supprimer cette facture ? Cette action est irréversible.",
      'invoices.confirm_link_title': 'Lier la facture',
      'invoices.confirm_link_message': 'Lier la facture',
      'invoices.confirm_link_to': 'à',
      'invoices.confirm_link_confirm': 'Lier',
      'invoices.modal.title_create': 'Créer une facture',
      'invoices.modal.title_edit': 'Modifier la facture',
      'invoices.modal.invoice_number': 'Numéro de facture',
      'invoices.modal.invoice_type': 'Type de facture',
      'invoices.modal.other_type': 'Autre',
      'invoices.modal.custom_type_placeholder': 'Saisir le type',
      'invoices.modal.client': 'Client',
      'invoices.modal.select_client': 'Sélectionner un client',
      'invoices.modal.bill_to': 'Facturer à',
      'invoices.modal.currency': 'Devise',
      'invoices.modal.rwf_label': 'RWF (Franc rwandais)',
      'invoices.modal.usd_label': 'USD (Dollar US)',
      'invoices.modal.invoice_total': 'Total de la facture',
      'invoices.modal.due_date': "Date d'échéance",
      'invoices.modal.description': 'Description',
      'invoices.modal.line_items': 'Articles',
      'invoices.modal.product_service_label': 'Produit / service',
      'invoices.modal.product_service': 'Produit ou service',
      'invoices.modal.qty': 'Qté',
      'invoices.modal.rate': 'Tarif',
      'invoices.modal.amount': 'Montant',
      'invoices.modal.add_line_item': 'Ajouter une ligne',
      'invoices.modal.subtotal': 'Sous-total',
      'invoices.modal.tax': 'Taxe',
      'invoices.modal.total': 'Total',
      'invoices.modal.invoice_item': 'Article de facture',
      'invoices.modal.save_draft': 'Enregistrer le brouillon',
      'invoices.modal.save_send': 'Enregistrer et envoyer',
      'invoices.modal.update_invoice': 'Mettre à jour la facture',
      'invoices.modal.cancel': 'Annuler',
    // Settings
    'settings.company_updated': "Entreprise mise à jour avec succès",
    'settings.company_update_error': "Échec de la mise à jour de l'entreprise",
    'settings.switched_to': 'Basculé vers',
    'settings.switch_error': "Échec du changement d'entreprise",
    'settings.workspace_created': "Nouvel espace créé avec succès",
    'settings.workspace_create_error': "Échec de la création de l'espace",
    'settings.payments_load_connections_error': "Échec du chargement des connexions d'alertes",
    'settings.payments_load_events_error': "Échec du chargement des événements",
    'settings.workspace_delete_active_error': "Vous ne pouvez pas supprimer l'espace actif.",
    'settings.workspace_deleted': "Espace supprimé avec succès :",
    'settings.workspace_delete_error': "Échec de la suppression de l'espace",
    'settings.identifier_required': 'Identifiant requis',
    'settings.connection_added': "Connexion d'alertes ajoutée",
    'settings.connection_create_error': 'Échec de création de la connexion',
    'settings.connection_deleted': 'Connexion supprimée',
    'settings.connection_delete_error': "Échec de la suppression de la connexion",
    'settings.loading': 'Chargement...',
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez vos préférences et paramètres',
    'settings.tab_company': "Profil de l'entreprise",
    'settings.tab_profile': 'Profil',
    'settings.tab_security': 'Sécurité',
    'settings.tab_branding': 'Branding',
    'settings.tab_workspaces': 'Espaces',
    'settings.tab_payments': 'Alertes de paiement',
    'settings.company_name': "Nom de l'entreprise",
    'settings.industry': 'Secteur',
    'settings.default_currency': 'Devise par défaut',
    'settings.tax_rate': 'Taux de taxe (%)',
    'settings.usd_exchange_rate': 'Taux de change USD',
    'settings.save_changes': 'Enregistrer les modifications',
    'settings.profile_title': 'Votre profil',
    'settings.profile_subtitle': 'Ces informations reflètent votre compte utilisateur.',
    'settings.workspaces_title': "Changer d'espace de travail",
    'settings.workspaces_subtitle': "Utilisez un seul e-mail pour plusieurs entreprises et choisissez l'espace à gérer.",
    'settings.create_workspace': 'Créer un nouvel espace',
    'settings.no_workspaces': "Aucun espace trouvé pour cet e-mail.",
    'settings.workspace_role': 'Rôle',
    'settings.workspace_current': 'Actuel',
    'settings.workspace_switching': 'Changement...',
    'settings.workspace_switch': 'Changer',
    'settings.workspace_delete_disabled': "Impossible de supprimer l'espace actif",
    'settings.workspace_delete': "Supprimer l'espace",
    'settings.workspace_deleting': 'Suppression...',
    'settings.workspace_cannot_delete': 'Suppression impossible',
    'settings.payments_connect_title': 'Connecter une boîte mail',
    'settings.payments_connect_subtitle': "Ajoutez une adresse e-mail pour ingérer les alertes.",
    'settings.payments_placeholder_gmail': 'alerts@votreentreprise.com',
    'settings.payments_display_name': "Nom d'affichage (optionnel)",
    'settings.payments_saving': 'Enregistrement...',
    'settings.payments_add_connection': 'Ajouter la connexion',
    'settings.payments_connected': 'Sources connectées',
    'settings.payments_refreshing': 'Actualisation...',
    'settings.payments_refresh': 'Actualiser',
    'settings.payments_loading_connections': 'Chargement des connexions...',
    'settings.payments_none': "Aucune connexion e-mail pour l'instant.",
    'settings.payments_removing': 'Suppression...',
    'settings.payments_remove': 'Supprimer',
    'settings.payments_events_title': 'Événements récents',
    'settings.payments_loading_events': 'Chargement des événements...',
    'settings.payments_no_events': "Aucun événement pour l'instant.",
    'settings.payments_subject': 'Sujet',
    'settings.payments_error': 'Erreur',
    'settings.create_workspace_title': 'Créer un nouvel espace',
    'settings.workspace_company_name': "Nom de l'entreprise",
    'settings.workspace_owner_email': "E-mail du propriétaire",
    'settings.workspace_owner_hint': "Utilise votre e-mail actuel",
    'settings.workspace_creating': 'Création...',
    'settings.save_title': 'Enregistrer les modifications',
    'settings.save_message': "Voulez-vous vraiment enregistrer ces modifications du profil d'entreprise ?",
    'settings.delete_workspace_title': "Supprimer l'espace",
    'settings.delete_workspace_message': 'Voulez-vous vraiment supprimer',
    'settings.this_workspace': 'cet espace',
    'settings.delete_workspace_warning': "Cela supprimera définitivement toutes les données et ne peut pas être annulé.",
    'settings.delete_workspace_confirm': "Supprimer l'espace",
  },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<LangCode>(() => {
    const stored = localStorage.getItem('finflow_lang') as LangCode;
    return stored === 'fr' ? 'fr' : 'en';
  });

  const setLang = (newLang: LangCode) => {
    setLangState(newLang);
    localStorage.setItem('finflow_lang', newLang);
  };

  const t = (key: string): string =>
    translations[lang][key] ?? translations['en'][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);




















